services:
  mariadb:
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    image: mariadb:latest
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/dumps/:/var/dumps
      - ./mariadb/my.cnf:/etc/mysql/conf.d/override.cnf
    labels:
      org.label-schema.group: "php_backend"

  mariadb_test:
    container_name: mariadb_test
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE_TEST}
      - MYSQL_USER=${MYSQL_USER_TEST}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_TEST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    image: mariadb:latest
    ports:
      - "${MYSQL_HOST_PORT_TEST}:3306"
    volumes:
      - ./mariadb_test/dumps/:/var/dumps
      - ./mariadb_test/my.cnf:/etc/mysql/conf.d/override.cnf
    labels:
      org.label-schema.group: "php_backend"

  php_fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
    container_name: php_fpm
    expose:
      - '9000'
    command: bash -c "/wait-for-it.sh mariadb:3306 -t 60 && /wait-for-it.sh mariadb_test:3306 && /wait-for-it.sh redis:6379 && /usr/sbin/php-fpm8.1"
    links:
      - mariadb
      - mariadb_test
      - redis
    depends_on:
      - mariadb
      - mariadb_test
      - redis
    volumes:
      - ../src:/var/www/adrianoff/php_backend
      - ./php-fpm/php.ini:/etc/php/8.1/fpm/conf.d/90-php_backend.ini
      - ./php-fpm/php.ini:/etc/php/8.1/cli/conf.d/90-php_backend.ini
      - ./php-fpm/local.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
      - ./php-fpm/local.ini:/etc/php/8.1/cli/conf.d/99-overrides.ini
    labels:
      org.label-schema.group: "php_backend"

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ../src:/var/www/adrianoff/php_backend
      - ${NGINX_CONFIG}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_CONFIG}/sites/:/etc/nginx/sites-available
      - ${NGINX_CONFIG}/conf.d/:/etc/nginx/conf.d
      - ${NGINX_CERT}:/etc/nginx-cert
      #- ./nginx/logs/:/var/log  ## Please use it when you need logging. Create nginx/error.log and nginx/access.log before start logging.
    privileged: true
    command: bash -c "/wait-for-it.sh php_fpm:9000 -t 120 && nginx"
    links:
      - php_fpm
    depends_on:
      - php_fpm
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    labels:
      org.label-schema.group: "php_backend"

  redis:
    container_name: redis
    image: redis
    labels:
      org.label-schema.group: "php_backend"

version: '3'
volumes: {}